import { describe, expect, it } from "@jest/globals";
import {
  ContentTypeSchema,
  DimensionVerdictSchema,
  FinalDecisionSchema,
  FixtureProvenanceSchema,
  IssueCategorySchema,
  ReviewerTypeSchema,
  ReviewActionTypeSchema,
  ReviewDimensionSchema,
  ReviewDepthSchema,
  ReviewEvidenceSourceSchema,
  ReviewDecisionSchema,
  ReviewStageSchema,
  RiskLevelSchema,
  SeveritySchema,
  SocialAccessModeSchema,
  SocialMediaTypeSchema,
  SocialPlatformSchema,
  SocialProviderStatusSchema,
} from "../../../src/pr-review/algorithm/index.js";

describe("ALG-001 public enums", () => {
  it.each([
    [
      ContentTypeSchema,
      [
        "SOCIAL_POST",
        "PRESS_RELEASE",
        "PRODUCT_LAUNCH",
        "BRAND_CAMPAIGN",
        "EXTERNAL_RESPONSE",
        "MULTIMODAL_POST",
      ],
    ],
    [
      ReviewDecisionSchema,
      ["APPROVE", "REVISE", "REJECT", "ESCALATE", "REVIEW_REQUIRED"],
    ],
    [RiskLevelSchema, ["LOW", "MEDIUM", "HIGH"]],
    [
      IssueCategorySchema,
      [
        "FACT",
        "BRAND",
        "COMPLIANCE",
        "REPUTATION",
        "VISUAL",
        "BRAND_VOICE",
        "PUBLIC_SENTIMENT",
        "CRISIS_RESPONSE",
        "RESPONSIBILITY_ATTRIBUTION",
        "COMPETITOR_ATTACK",
        "CONTEXTUAL_MISINTERPRETATION",
        "PLATFORM_SUITABILITY",
        "ACCOUNT_POSITIONING",
        "CAMPAIGN_CONSISTENCY",
        "PLATFORM_RULE",
        "CTA_URL_HASHTAG",
        "ASSET_COMPLETENESS",
        "CROSS_PLATFORM_ADAPTATION",
        "PUBLISHING_CONTEXT",
        "PRODUCT_NAME",
        "PRODUCT_SPECIFICATION",
        "PRODUCT_CAPABILITY",
        "PRODUCT_PRICE",
        "PRODUCT_AVAILABILITY",
        "PRODUCT_VERSION",
        "PERFORMANCE_CLAIM",
        "DATA_CLAIM",
        "COMPARATIVE_CLAIM",
        "THIRD_PARTY_CITATION",
        "UNSUPPORTED_PRODUCT_CLAIM",
        "CUSTOMER_EXPECTATION",
        "SERVICE_COMMITMENT",
        "AFTER_SALES_COMMITMENT",
        "COMPENSATION_IMPLICATION",
        "CUSTOMER_COMPLAINT_SENSITIVITY",
        "KNOWN_PRODUCT_ISSUE",
        "AUDIENCE_OFFENSE",
        "EXPERIENCE_GAP",
        "COMPLAINT_ESCALATION",
        "ADVERTISING_COMPLIANCE",
        "ABSOLUTE_MARKETING_CLAIM",
        "MISLEADING_CLAIM",
        "PRIVACY",
        "CONFIDENTIAL_INFORMATION",
        "PERSONAL_INFORMATION",
        "INTELLECTUAL_PROPERTY",
        "SENSITIVE_CONTENT",
        "ILLEGAL_HARMFUL_CONTENT",
        "PLATFORM_CONTENT_SAFETY",
        "ADVERTISEMENT_IDENTIFICATION",
      ],
    ],
    [SeveritySchema, ["LOW", "MEDIUM", "HIGH", "CRITICAL"]],
    [ReviewerTypeSchema, ["RULE", "LLM", "VISUAL", "HUMAN", "AGGREGATOR"]],
    [
      ReviewActionTypeSchema,
      [
        "APPROVE",
        "REVISE",
        "REJECT",
        "ESCALATE",
        "SUBMIT",
        "AUTO_ROUTE",
        "SCHEDULE",
      ],
    ],
    [
      ReviewStageSchema,
      [
        "REQUESTER_SELF_CHECK",
        "OPERATOR_REVIEW",
        "VISUAL_REVIEW",
        "COMPLIANCE_REVIEW",
        "RISK_ROUTING",
        "MEDIA_MANAGER_APPROVAL",
        "SCHEDULING",
        "COMPLETED",
        "REJECTED",
        "ESCALATED",
        "REVIEW_REQUIRED",
      ],
    ],
    [
      SocialPlatformSchema,
      ["weibo", "xiaohongshu", "douyin", "bilibili", "coolapk"],
    ],
    [
      SocialAccessModeSchema,
      ["official_api", "authorized_export", "local_fixture", "disabled"],
    ],
    [
      FixtureProvenanceSchema,
      ["synthetic", "manually_curated", "authorized_export"],
    ],
    [SocialMediaTypeSchema, ["text", "image", "video", "mixed", "unknown"]],
    [SocialProviderStatusSchema, ["available", "partial", "unavailable"]],
    [
      ReviewDimensionSchema,
      [
        "PUBLIC_RELATIONS",
        "OPERATIONS",
        "PRODUCT",
        "CUSTOMER",
        "COMPLIANCE_SAFETY",
      ],
    ],
    [ReviewDepthSchema, ["LIGHT", "FULL"]],
    [DimensionVerdictSchema, ["PASS", "WARN", "BLOCK", "REVIEW_REQUIRED"]],
    [FinalDecisionSchema, ["PASS", "REVISE", "HUMAN_REVIEW", "BLOCK"]],
    [
      ReviewEvidenceSourceSchema,
      [
        "BRAND_KNOWLEDGE",
        "HISTORICAL_PR_CASES",
        "PLATFORM_POLICY",
        "CAMPAIGN_BRIEF",
        "ACCOUNT_PROFILE",
        "PRODUCT_KNOWLEDGE",
        "APPROVED_CLAIMS",
        "SOCIAL_CONTEXT",
        "CUSTOMER_FAQ",
        "SERVICE_POLICY",
        "MULTIMODAL_EVIDENCE",
      ],
    ],
  ] as const)("accepts the complete legal value set %#", (schema, values) => {
    for (const value of values) expect(schema.parse(value)).toBe(value);
  });

  it.each([
    ContentTypeSchema,
    ReviewDecisionSchema,
    RiskLevelSchema,
    IssueCategorySchema,
    SeveritySchema,
    ReviewerTypeSchema,
    ReviewActionTypeSchema,
    ReviewStageSchema,
    SocialPlatformSchema,
    SocialAccessModeSchema,
    FixtureProvenanceSchema,
    SocialMediaTypeSchema,
    SocialProviderStatusSchema,
    ReviewDimensionSchema,
    ReviewDepthSchema,
    DimensionVerdictSchema,
    FinalDecisionSchema,
    ReviewEvidenceSourceSchema,
  ])("rejects an unknown value %#", (schema) => {
    expect(schema.safeParse("UNKNOWN_CONTRACT_VALUE").success).toBe(false);
  });
});
